import numpy as np
from PIL import Image, ImageDraw

# Constraint produces curvature: two trajectories pressed against a diagonal
# The curve is generated by the tension, not the freedom

W, H = 1024, 1024
img = Image.new('RGB', (W, H), 'black')
draw = ImageDraw.Draw(img)

# The diagonal constraint: y = x + offset, offset varies
# Each trajectory wants to go straight but is deflected by the constraint
n_points = 120
t = np.linspace(0, 1, n_points)

# Base diagonal line
constraint_offset = 40
for offset in [0, 40, 80]:
    draw.line([(offset, offset), (W - offset, H - offset)], fill='gray', width=1)

# Trajectories that bow outward under constraint
# Starting from left edge, ending at top edge
# The constraint diagonal pushes them into a curve
for i in range(20):
    start_x = 0
    start_y = 200 + i * 30
    end_x = 200 + i * 5
    end_y = 0

    # The constraint point: where the trajectory would cross the diagonal
    # but bows away, creating a visible curve
    bow_amount = 30 + (i % 5) * 10
    mid_x = (start_x + end_x) / 2 - bow_amount
    mid_y = (start_y + end_y) / 2 - bow_amount

    color = int(100 + 20 * (i % 7))
    c = (color, color + 10, color + 20)

    draw.line([(start_x, start_y), (mid_x, mid_y)], fill=c, width=1)
    draw.line([(mid_x, mid_y), (end_x, end_y)], fill=c, width=1)

# The bowed trajectories form a fan of curves pressing against the diagonal
# The diagonal is the constraint; the curves are what happens when you can't pass

img.save('assets/constraint-fan.png')
print("done")
