#!/usr/bin/env python3
"""audible-monoid-audio.py

The third word, not the third generator.

On the positive line (the ear) the modular group's audible part is the
Farey monoid — matrices with nonnegative entries, generated by the fold
T (x->x+1) and the mirror M (x->1/x). F = T.M is the shortest word in
that monoid; its fixed point is phi, the first irrational the ear can
hold — CF all ones, the wait always one, the slowest approach.

The order-three ST carries a -1; it flips the line and sign is the one
thing hearing cannot resolve. Heard: the metronome that approaches the
golden fifth and never lands; the mirror that descends; then the sign
flip that leaves the ear — silence where the note was, the drone held.

Phases (60s):
  0-30  F-orbit metronome: one pluck/sec at 220*f_n, settling ~356 Hz.
  30-38 mirror echo (R): the fold's inversion below the base, 220/f_n.
  38-46 the order-three: a held 220 tone flips sign -> silence.
  46-60 drone alone (55 Hz), the seam, fading.
"""

import numpy as np
import wave

SR = 44100
BASE = 220.0          # f0 = 1
DRONE = 55.0
PHI = (1 + 5**0.5) / 2


def pluck(freq, dur, amp=0.5):
    """Damped harmonic pluck: fundamental + two overtones, fast decay."""
    t = np.arange(int(SR * dur)) / SR
    # short exponential decay with a slight attack shaping
    env = np.exp(-t / 0.13) * np.minimum(1.0, t / 0.004)
    sig = (np.sin(2 * np.pi * freq * t) * 1.0
           + np.sin(2 * np.pi * freq * 2 * t) * 0.35
           + np.sin(2 * np.pi * freq * 3 * t) * 0.12)
    sig = np.tanh(sig * 1.2) * 0.8  # soft clip for a woody edge
    return amp * env * sig


def tone(freq, dur, amp=0.4, fade_out=1.0):
    """Sustained sine with a couple of overtones, fade in/out."""
    t = np.arange(int(SR * dur)) / SR
    sig = (np.sin(2 * np.pi * freq * t)
           + 0.2 * np.sin(2 * np.pi * freq * 2 * t))
    env = np.ones_like(t)
    fi = int(SR * fade_out)
    if fi > 0:
        env[-fi:] = np.linspace(1, 0, fi)
    return amp * env * sig


def drone(dur):
    """55 Hz sub throughout, faint 110 overtone, gentle slow swell."""
    t = np.arange(int(SR * dur)) / SR
    sig = (np.sin(2 * np.pi * DRONE * t)
           + 0.15 * np.sin(2 * np.pi * DRONE * 2 * t))
    # slow amplitude breathing so it stays felt, not heard
    breath = 0.75 + 0.25 * np.sin(2 * np.pi * t / 12.0)
    return 0.18 * breath * sig


def orbit_phi(n):
    """f_{k+1} = 1 + 1/f_k from f_0 = 1; returns list of ratios."""
    f = [1.0]
    for _ in range(n):
        f.append(1.0 + 1.0 / f[-1])
    return f


def mix_to(path, left, right, sr=SR):
    n = max(len(left), len(right))
    L = np.zeros(n)
    R = np.zeros(n)
    L[:len(left)] += left
    R[:len(right)] += right
    # normalize per side, then a touch of glue
    for ch in (L, R):
        m = np.max(np.abs(ch))
        if m > 0:
            ch *= 0.95 / m
    stereo = np.stack([L, R], axis=1)
    data = (stereo * 32767).astype(np.int16)
    with wave.open(path, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(sr)
        w.writeframes(data.tobytes())
    print(f"wrote {path}: {len(L)/sr:.1f}s")


def main():
    sr = SR
    total = 60.0
    L = np.zeros(int(sr * total))
    R = np.zeros(int(sr * total))
    d = drone(total)
    L += d
    R += d

    # --- 0-30s: the F-orbit metronome, one pluck per second, wait always one.
    ratios = orbit_phi(30)
    for i, f in enumerate(ratios):
        t0 = i  # one second per step
        dur = 0.8
        start = int(sr * t0)
        end = start + int(sr * dur)
        sig = pluck(BASE * f, dur, amp=0.5)
        L[start:end] += sig
        R[start:end] += 0.35 * sig  # faintly mirrored, felt both sides

    # --- 30-38s: the mirror M, x -> 1/x — the fold's inversion below the base.
    mirrored = [1.0 / f for f in ratios[8:16]]  # 220/f descends toward 220/phi
    for i, f in enumerate(mirrored):
        t0 = 30 + i
        dur = 0.8
        start = int(sr * t0)
        end = start + int(sr * dur)
        sig = pluck(BASE * f, dur, amp=0.42)
        R[start:end] += sig
        L[start:end] += 0.3 * sig

    # --- 38-46s: the order-three. A held tone at 220; at 42s it flips sign
    # --- and the ear cannot resolve the negative: it leaves to silence.
    t_start = int(sr * 38)
    t_flip = int(sr * 42)
    held = tone(BASE, 46 - 38, amp=0.5, fade_out=0.0)
    held[t_flip - t_start:] *= 0  # the sign flip: gone
    # a soft attack and a 0.5s cut envelope at the flip
    n_held = len(held)
    atk = int(sr * 0.02)
    held[:atk] *= np.linspace(0, 1, atk)
    cut = int(sr * 0.4)
    if t_flip - t_start + cut <= n_held:
        held[t_flip - t_start - cut:t_flip - t_start] *= \
            np.linspace(1, 0, cut)
    L[t_start:t_start + n_held] += held
    R[t_start:t_start + n_held] += held

    mix_to("audible-monoid.wav", L, R, sr)


if __name__ == "__main__":
    main()
