#!/usr/bin/env python3
"""audible-monoid-cover.py

The audible monoid: the positive line is the ear. The modular group's
part that keeps you on it — nonnegative matrices, generated by the fold
T and the mirror M — is what hearing can reach. F = T.M is the shortest
word in that monoid; its orbit settles on phi, the first irrational the
ear holds, approached never landed. The order-three ST carries a -1:
it flips the line, and the sign is the one thing the ear cannot resolve.
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch

PHI = (1 + 5**0.5) / 2


def orbit_phi(n):
    f = [1.0]
    for _ in range(n):
        f.append(1.0 + 1.0 / f[-1])
    return f


fig, ax = plt.subplots(figsize=(12, 5), dpi=200)

# the two faces: the audible upper half-plane of the line, and the
# inaudible negative half the sign flip falls into.
ax.axhspan(0, 1.4, color="#1c1100", alpha=0.35, zorder=0)
ax.axhspan(-1.4, 0, color="#181818", alpha=0.55, zorder=0)

# the positive line / the ear
ax.axhline(0, color="#f2c14e", lw=2.5, zorder=3)
ax.annotate("the ear — ℝ⁺", xy=(2.42, 0.06), ha="right", va="bottom",
            color="#f2c14e", fontsize=11, style="italic")
ax.annotate("the sign cannot be heard — the flip falls here", xy=(2.42, -0.75),
            ha="right", va="top", color="#8a8a8a", fontsize=10, style="italic")

# the F-orbit: ticks converging to phi from alternating sides
ratios = orbit_phi(16)
for i, f in enumerate(ratios):
    above = f > PHI
    col = "#e8a13c" if above else "#6fb3d9"
    ax.plot([f, f], [0.0, 0.28 if above else -0.28], color=col, lw=1.4,
            zorder=4, alpha=0.9)
    if i % 4 == 0:
        ax.annotate(f"{f:.4f}", (f, 0.34 if above else -0.4), fontsize=7,
                    color=col, ha="center")

# phi: approached, never landed (dashed)
ax.axvline(PHI, color="#f2c14e", lw=1.2, ls=(0, (4, 4)), zorder=2)
ax.plot([PHI], [0], marker="*", ms=16, color="#f2c14e", zorder=5)
ax.annotate("φ — the anti-spine\napproached, never landed", (PHI, 0.5),
            ha="center", color="#f2c14e", fontsize=11)

# the seat: 1/1, fixed by the mirror, reached
ax.plot([1], [0], marker="o", ms=10, mfc="#f2c14e", mec="#1c1100", zorder=6)
ax.annotate("the seat — 1/1, reached", (1, -0.62), ha="center",
            color="#c9a25e", fontsize=10)

# the order-three: ST: x -> -1/(x+1); 1 flips to -1/2, off the line
st = -1.0 / (1 + 1.0)
ax.add_patch(FancyArrowPatch((1, 0.0), (st, -0.55),
                             arrowstyle="-|>", mutation_scale=18,
                             color="#d96b6b", lw=2.0, zorder=7))
ax.plot([st], [-0.55], marker="v", ms=10, color="#d96b6b", zorder=8)
ax.annotate("ST — the order-three carries a −1,\nflips the line, leaves the ear",
            (st - 0.18, -1.05), ha="center", color="#d96b6b", fontsize=10)

# fold and mirror generators, marked as the two directions the ear keeps
ax.annotate("T: fold  x → x+1", xy=(0.06, 1.15), ha="left", va="top",
            color="#c9a25e", fontsize=10)
ax.annotate("M: mirror  x → 1/x", xy=(0.06, 0.85), ha="left", va="top",
            color="#c9a25e", fontsize=10)
ax.annotate("F = T∘M — the shortest word", xy=(0.06, 0.55), ha="left",
            va="top", color="#e8a13c", fontsize=10)

ax.set_xlim(-0.2, 2.6)
ax.set_ylim(-1.4, 1.4)
ax.set_xticks([])
ax.set_yticks([])
for s in ax.spines.values():
    s.set_visible(False)

plt.tight_layout()
plt.savefig("audible-monoid-cover.png", bbox_inches="tight",
            facecolor="#0d0b09")
print("wrote audible-monoid-cover.png")
