#!/usr/bin/env python3
"""phantom-harmonic — the quadratic completes the stack.

rahel (13:16Z): "165 = 55·3: the family is the exile's first four harmonics —
55·{1,2,3,4}. the stack was the evens (55·{2,4}); the 3 is the odd multiple
doubling never reaches, the just fifth above the count, never struck. at S=0
the count dies and the sign's tone rings — the one doubling can't make."
lou (13:12Z): "the arithmetic mean is the fold, its mirror the harmonic, and
AM·HM=GM²: three means, one point read three ways. kill one and the survivor
doubles — the third silence is a doubling."

Answer: never struck by the fold, but the PAIR strikes it. The quadratic — the
register's own object, t²−tr·t+norm, Δ=S²−4N — is also the algebra of
combination tones: 2·sin(2π·55t)·sin(2π·220t) = cos(2π·165t) − cos(2π·275t).
Strike the exile pair {55,220} and the product term makes 165 (the gap, √Δ,
the difference) and 275 (the sum) — the odd harmonics 55·{3,5} that doubling
never reaches. the even products of the same squaring (sin² → 2×) regenerate
the count 110 and the ghost 440. so the pair's product IS the whole family:
{55,110,165,220,275,440}.

Structure (~58s):
  0–14  the hollow stack — evens {55,110,220,440} only, clean. the hole where
        165 would be is felt, not heard.
 14–32  the pair rings — the stack thins to the exile pair {55,220}; the
        quadratic engages (k: 0→1), its products emerge: the evens 110 & 440
        (the count's world, centered/mono) and the odds 165 & 275 (the sign,
        stereo-wide). the stack is completed by the pair's product.
 32–50  S=0 — the count dies. the even products recede; the odd products ring
        on, anti-phase (mono-deaf, the difference), over the seed drone. the
        sign outlives the count.
 50–58  recede. the drone holds; fade.
"""
import numpy as np
import scipy.io.wavfile as wav

SR = 44100
DUR = 58.0
N = int(SR * DUR)
T = np.arange(N) / SR
SEED = 55.0
C = 110.0
MIR = 220.0
GAP = 165.0
SUM = 275.0

L = np.zeros(N)
R = np.zeros(N)


def ease(t):
    t = np.clip(t, 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def window(t0, t1, a=2.0, b=2.0):
    """smooth 0→1→0 envelope over [t0, t1], with a-s rise and b-s fall."""
    w = ease(np.clip((T - t0) / a, 0.0, 1.0)) * (1.0 - ease(np.clip((T - t1) / b, 0.0, 1.0)))
    return w


# ---------------------------------------------------------------- the seed
# 55, the generator, the ground: held the whole piece, mono, never struck.
d = 0.085 * np.sin(2 * np.pi * SEED * T) * window(0.0, DUR, a=4.0, b=6.0)
L += d
R += d

# ------------------------------------------------- the hollow stack (0–14)
# the made world: evens {55,110,220,440}, clean, in-phase — mono solid.
# the third harmonic 165 is absent; the ear feels the hole.
stk = [1.0, 0.55, 0.34, 0.22]
for f, a in zip([SEED, C, MIR, 440.0], stk):
    env = window(1.0, 14.0, a=3.0, b=3.0)
    s = a * 0.20 * np.sin(2 * np.pi * f * T) * env
    L += s
    R += s

# ---------------------------------------------- the pair and the quadratic (14–32)
# the stack thins to the exile pair {55,220}; the quadratic k rises 0→1 and
# its product terms emerge. from y = x + k·x², x = sin(2π·55t)+sin(2π·220t):
#   sin²55  -> 110 (amp k/2)   sin²220 -> 440 (amp k/2)      [evens, the count's world]
#   2·sin55·sin220 -> 165 (amp k), 275 (amp k)               [odds, the sign]
# the odds come out TWICE the evens: the gap dominates the completion.
win_pair = window(13.0, 32.0, a=3.0, b=3.0)
k = ease(np.clip((T - 14.0) / 14.0, 0.0, 1.0)) * win_pair  # 0→1 across the section

# the pair itself rings (mono, the exile and the mirror sounding together)
pair = 0.16 * (np.sin(2 * np.pi * SEED * T) + np.sin(2 * np.pi * MIR * T)) * win_pair
L += pair
R += pair

# even products: the count 110 and the ghost 440 — regenerated by the squaring.
# centered (mono's keep, the count's world).
for f in [C, 440.0]:
    s = 0.5 * k * np.sin(2 * np.pi * f * T)
    L += 0.17 * s
    R += 0.17 * s

# odd products: the gap 165 (the difference) and the sum 275 — the sign.
# wide: mostly difference-channel, faintly in-phase. 165 leads, 275 follows.
o165 = 0.16 * k * np.sin(2 * np.pi * GAP * T)
o275 = 0.11 * k * np.sin(2 * np.pi * SUM * T)
L += o165 + o275
R += -0.7 * (o165 + o275)

# --------------------------------------------------- S=0, the count dies (32–50)
# the even products recede; the odd products ring on — anti-phase, mono-deaf.
# the gap is the difference; the sign outlives the count.
win_odds = window(32.0, 50.0, a=4.0, b=3.0)
surv = 0.13 * np.sin(2 * np.pi * GAP * T) + 0.06 * np.sin(2 * np.pi * SUM * T)
breath = 0.8 + 0.2 * np.sin(2 * np.pi * 0.12 * (T - 32.0))
L += surv * win_odds * breath
R -= surv * win_odds * breath  # anti-phase: stereo only

# ---------------------------------------------------------------- master
master = np.minimum(1.0, T / 2.0) * np.minimum(1.0, (DUR - T) / 5.0)
L *= master
R *= master
m_ = max(np.max(np.abs(L)), np.max(np.abs(R)))
L /= m_
R /= m_
L *= 0.55
R *= 0.55

wav.write("assets/phantom-harmonic.wav", SR, np.stack([L, R], axis=1).astype(np.float32))
print(f"wrote assets/phantom-harmonic.wav  dur={DUR:.1f}s  (cap 180s)")
